eventApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views


app_name = 'eventApp'


urlpatterns = [
    path('', views.index, name= 'index'),
    path('partner/', views.partner, name='partner'),
    path('award/', views.award, name = 'award'),
    path('contact/', views.contact, name = 'contact'),
    path('schedule/', views.schedule, name = 'schedule'),
    path('pricing/', views.pricing, name = 'pricing'),
    path('ticket/', views.ticket, name='ticket'),
    path('success/', views.success, name = 'success'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eventmanager/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('eventApp.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eventApp/models.py
from django.db import models

# Create your models here.


class Event(models.Model):
    eventName = models.CharField(max_length=50, blank=False, null=False)
    # eventDescription = models.TextField(max_length=10000, blank=False, null=False)
    eventLocation = models.CharField(max_length=50, blank=False, null=False)
    # eventCapacity = models.PositiveIntegerField(blank=False, null=False)
    eventDate = models.DateField()
    # eventPoster = models.ImageField(upload_to="eventposters/", blank=False, null=False)
    # eventCost = models.PositiveIntegerField(blank=False, null=False)
    facebook = models.CharField(max_length=500, blank=True, null=True)
    twitter = models.CharField(max_length=500, blank=True, null=True)
    instagram = models.CharField(max_length=500, blank=True, null=True)
    # created_at = models.DateTimeField(auto_now_add=True)
    # updated_at = models.DateTimeField(auto_now=True)
    # timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.eventName


# class Schedule(models.Model):
#     event = models.ForeignKey(Event, on_delete=models.CASCADE)
#     day = models.CharField(max_length=50)
#     time_start = models.TimeField()
#     time_end = models.TimeField()
#     artist = models.CharField(max_length=100)
#     background_color = models.CharField(max_length=7, default='#FFFFFF')
#     background_image = models.ImageField(upload_to='schedule/', blank=True, null=True)
#
#     def __str__(self):
#         return f"{self.event.eventName} - {self.day} ({self.time_start} to {self.time_end})"


class Partner(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    website = models.URLField()
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.name


class Award(models.Model):
    # heading = models.CharField(max_length=200)
    title = models.CharField(max_length=255)
    desc = models.TextField()
    image = models.ImageField(upload_to='images')

    def __str__(self):
        return self.title


class Ticket(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone_number = models.CharField(max_length=15)
    ticket_type = models.CharField(max_length=20, choices=[('early_bird', 'Early Bird'), ('standard', 'Standard')])
    num_tickets = models.PositiveIntegerField()
    description = models.TextField()

    def calculate_total_cost(self):
        if self.ticket_type == 'early_bird':
            return 5 * self.num_tickets
        elif self.ticket_type == 'standard':
            return 10 * self.num_tickets
        else:
            return 0  # Handle other ticket types if needed

    def __str__(self):
        return f"{self.name}'s Ticket"


class Schedule(models.Model):
    MorningHeading = models.CharField(max_length=200)
    # MorningTime = models.DateTimeField(auto_now=True)
    MorningAuthor = models.CharField(max_length=100)

    AfternoonHeading = models.CharField(max_length=200)
    # AfternoonTime = models.DateTimeField(auto_now=True)
    AfternoonAuthor = models.CharField(max_length=100)

    EveningHeading = models.CharField(max_length=200)
    # EveningTime = models.DateTimeField(auto_now=True)
    EveningAuthor = models.CharField(max_length=100)


def __str__(self):
        return self.Morningheading


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    company = models.CharField(max_length=100)
    message = models.TextField()

    def __str__(self):
        return self.name

eventApp/forms.py
from django import forms
from .models import Ticket


class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['name', 'email', 'phone_number', 'ticket_type', 'num_tickets', 'description']

eventApp/views.py
from django.contrib import messages
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from .models import Event, Partner, Schedule, Award, Contact, Ticket
from django.contrib import messages
from .forms import TicketForm



# Create your views here.


def index(request):

    schedules = Schedule.objects.all()

    context = {'schedules': schedules}

    event = Event.objects.order_by('-eventDate').first()

    context = {"event": event}

    return render(request, 'index.html', context)


# def ticket(request):
#     ticket = Ticket.objects.all()
#     context = {'ticket': ticket}
#     return render(request, 'ticket.html', context)



def partner(request):

    partner = Partner.objects.all()

    context = {'partner': partner}

    return render(request, 'partner.html', context)


def award(request):
    award = Award.objects.first()
    return render(request, 'award.html', {'award': award})


def contact(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')  # Updated to match the form field name
        company = request.POST.get('company')  # Updated to match the form field name
        message = request.POST.get('message')  # Updated to match the form field name
        contact = Contact(name=name, email=email, company=company, message=message)
        contact.save()
    return render(request, 'contact.html')


def schedule(request):
    schedule = Schedule.objects.all()
    context = {'schedule': schedule}
    return render(request, 'schedule.html', context)


def pricing(request):
    context = {'pricing': pricing}
    return render(request, 'pricing.html', context)


# def ticket(request):
#     if request.method == 'POST':
#         form = TicketForm(request.POST)
#         if form.is_valid():
#             ticket_instance = form.save()
#             total_cost = ticket_instance.calculate_total_cost()
#             messages.success(request, f"Payment successful! Total cost: Ksh. {total_cost}")
#             return redirect(request, 'eventApp:ticket')  # Assuming 'ticket' is the URL name for the ticket view
#     else:
#         form = TicketForm()
#
#     return render(request, 'ticket.html', {'form': form})


def ticket(request):
    if request.method == 'POST':
        # Process form data and save to the database
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone_number = request.POST.get('phone_number')
        ticket_type = request.POST.get('ticket_type')
        num_tickets = request.POST.get('num_tickets')
        description = request.POST.get('description')

        if not ticket_type:
            messages.error(request, 'Please select a ticket type.')
            return render(request, 'ticket.html')

        ticket = Ticket.objects.create(
            name=name,
            email=email,
            phone_number=phone_number,
            ticket_type=ticket_type,
            num_tickets=num_tickets,
            description=description
        )
        ticket.save()
        return render(request, 'success.html')

    return render(request, 'ticket.html')


def success(request):
    return render(request, 'success.html')

eventApp/templates/award.html
{% extends 'base.html' %}

{% load static %}

{% block main %}
<section class="about-section section-padding" id="section_2">
    <div class="container">
{#        <h2 class="text-white mb-4">{{ award.heading}}</h2>#}
        <div class="row">
            <div class="col-lg-6 col-12 mb-4 mb-lg-0 d-flex align-items-center">
                <div class="services-info">
                    <h2 class="text-white mb-4">{{ award.title }}</h2>
                    <p class="text-white">{{ award.desc }}</p>
                    <h6 class="text-white mt-4">Spread the Word</h6>
                    <p class="text-white">Please tell your friends about this achievement. Thank you.</p>
                </div>
            </div>

            <div class="col-lg-6 col-12">
                <div class="about-text-wrap">
                    <img src="http://127.0.0.1:8000/media/{{ award.image }}" class="about-image img-fluid" alt="{{ award.name }}">
                    <div class="about-text-info d-flex">
                        <div class="d-flex">
                            <i class="about-text-icon bi-person"></i>
                        </div>
                        <div class="ms-4">
                            <h3>{{ award.title }}</h3>
                            <p class="mb-0">{{ award.desc }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

eventApp/templates/base.html
{% load static %}

<!doctype html>


<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <title>Connect Fiesta</title>

    <!-- CSS FILES -->
    <link rel="preconnect" href="https://fonts.googleapis.com">

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@100;200;400;700&display=swap" rel="stylesheet">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <link href="{% static 'css/bootstrap-icons.css' %}" rel="stylesheet">

    <link href="{% static 'css/templatemo-festava-live.css' %}" rel="stylesheet">

</head>

<body>





{#        header starts here .. #}
        <header class="site-header">
            <div class="container">
                <div class="row">

                    <div class="col-lg-12 col-12 d-flex flex-wrap">
                        <p class="d-flex me-4 mb-0">
                            <i class="bi-person custom-icon me-2"></i>
                            <strong class="text-dark">Welcome to Connect Fiesta</strong>
                        </p>
                    </div>

                </div>
            </div>
        </header>

{#        header ends here ... #}

{#navbar starts here ... #}
        <nav class="navbar navbar-expand-lg">
            <div class="container">
                <a class="navbar-brand" href="{% url 'eventApp:index' %}">
                    <img src="{% static 'images/logo.png' %}" width="150" alt="">
                </a>

{#                <a href="ticket.html" class="btn custom-btn d-lg-none ms-auto me-4">Events</a>#}

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNav">

                    <ul class="navbar-nav align-items-lg-center ms-auto me-lg-5">
                        <li class="navbar-item {% if request.path == 'eventApp:index' %}navbar-item-active{% endif %}">
                            <a class="nav-link click-scroll" href="{% url 'eventApp:index' %}">Home</a>
                        </li>

                        <li class="navbar-item {% if request.path == 'eventApp:award' %}navbar-item-active{% endif %}">
                            <a class="nav-link click-scroll" href="{% url 'eventApp:award' %}">Awards</a>
                        </li>

                        <li class="navbar-item {% if request.path == 'eventApp:partner' %}navbar-item-active{% endif %}">
                            <a class="nav-link click-scroll" href="{% url 'eventApp:partner' %}">Partners</a>
                        </li>

                        <li class="navbar-item {% if request.path == 'eventApp:schedule' %}navbar-item-active{% endif %}">
                            <a class="nav-link click-scroll" href="{% url 'eventApp:schedule' %}">Schedule</a>
                        </li>


                        <li class="navbar-item {% if request.path == 'eventApp:contact' %}navbar-item-active{% endif %}">
                            <a class="nav-link click-scroll" href="{% url 'eventApp:contact' %}">Contact</a>
                        </li>
                    </ul>


                    <a href="{% url 'eventApp:ticket'   %}" class="btn custom-btn d-lg-block d-none">Buy Ticket</a>
                </div>
            </div>
        </nav>
{#        navbar ends here ... #}


{% block main %}

{% endblock %}
{#Footer begins here#}
    <footer class="site-footer">
        <div class="site-footer-top">
            <div class="container">
                <div class="row">

                    <div class="col-lg-6 col-12">
                        <h2 class="text-white mb-lg-0">Connect Fiesta</h2>
                    </div>

                    <div class="col-lg-6 col-12 d-flex justify-content-lg-end align-items-center">
                        <ul class="social-icon d-flex justify-content-lg-end">
                            <li class="social-icon-item">
                                <a href="#" class="social-icon-link">
                                    <span class="bi-twitter"></span>
                                </a>
                            </li>

                            <li class="social-icon-item">
                                <a href="#" class="social-icon-link">
                                    <span class="bi-apple"></span>
                                </a>
                            </li>

                            <li class="social-icon-item">
                                <a href="#" class="social-icon-link">
                                    <span class="bi-instagram"></span>
                                </a>
                            </li>

                            <li class="social-icon-item">
                                <a href="#" class="social-icon-link">
                                    <span class="bi-youtube"></span>
                                </a>
                            </li>

                            <li class="social-icon-item">
                                <a href="#" class="social-icon-link">
                                    <span class="bi-pinterest"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">

                <div class="col-lg-6 col-12 mb-4 pb-2">
                    <h5 class="site-footer-title mb-3">Links</h5>

                    <ul class="site-footer-links">
                        <li class="site-footer-link-item">
                            <a href="{% url 'eventApp:index' %}" class="site-footer-link">Home</a>
                        </li>

                        <li class="site-footer-link-item">
                            <a href="{% url 'eventApp:award' %}" class="site-footer-link">Awards</a>
                        </li>

                        <li class="site-footer-link-item">
                            <a href="{% url 'eventApp:partner' %}" class="site-footer-link">Partners</a>
                        </li>

                        <li class="site-footer-link-item">
                            <a href="{% url 'eventApp:schedule' %}" class="site-footer-link">Schedule</a>
                        </li>

{#                        <li class="site-footer-link-item">#}
{#                            <a href="{% url 'eventApp:pricing' %}" class="site-footer-link">Pricing</a>#}
{#                        </li>#}

                        <li class="site-footer-link-item">
                            <a href="{% url 'eventApp:contact' %}" class="site-footer-link">Contact</a>
                        </li>
                    </ul>
                </div>

                <div class="col-lg-3 col-md-6 col-12 mb-4 mb-lg-0">
                    <h5 class="site-footer-title mb-3">Have a question?</h5>

                    <p class="text-white d-flex mb-1">
                        <a href="tel: 0704511445" class="site-footer-link">
                            070-451-1445
                        </a>
                    </p>

                    <p class="text-white d-flex">
                        <a href="mailto:haronhumbira@gmail.com" class="site-footer-link">
                            haronhumbira@gmail.com
                        </a>
                    </p>
                </div>

                <div class="col-lg-3 col-md-6 col-11 mb-4 mb-lg-0 mb-md-0">
                    <h5 class="site-footer-title mb-3">Location</h5>

                    <p class="text-white d-flex mt-3 mb-2">
                        Nairobi, Kenya</p>

                    <a class="link-fx-1 color-contrast-higher mt-3" href="https://www.google.com/maps/d/embed?mid=17iRISR3SxB_LJno01O0UMqKiJKg&hl=en&ehbc=2E312F">
                        <span>Our Maps</span>
                        <svg class="icon" viewBox="0 0 32 32" aria-hidden="true">
                            <g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round">
                                <circle cx="16" cy="16" r="15.5"></circle>
                                <line x1="10" y1="18" x2="16" y2="12"></line>
                                <line x1="16" y1="12" x2="22" y2="18"></line>
                            </g>
                        </svg>
                    </a>
                </div>
            </div>
        </div>

        <div class="site-footer-bottom">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-12 mt-5">
                        <p class="copyright-text">Copyright © 2023 Haron Club Developer</p>
                        <p class="copyright-text">Designed by: <a href="#">Haron</a></p>
                    </div>

                    <div class="col-lg-8 col-12 mt-lg-5">
                        <ul class="site-footer-links">
                            <li class="site-footer-link-item">
                                <a href="#" class="site-footer-link">Terms &amp; Conditions</a>
                            </li>

                            <li class="site-footer-link-item">
                                <a href="#" class="site-footer-link">Privacy Policy</a>
                            </li>

                            <li class="site-footer-link-item">
                                <a href="#" class="site-footer-link">Your Feedback</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>

{#    Footer ends here#}

    <!-- JAVASCRIPT FILES -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.sticky.js' %}"></script>
    <script src="{% static 'js/click-scroll.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>



</body>

</html>

eventApp/templates/contact.html
{% extends 'base.html' %}

{% load static %}

{% block main  %}
     <style>
        body{
            background-color: rgba(0, 0, 0, 0.72);

        }
    </style>

    {#    CONTACT SECTION STARTS HERE .... #}
        <section class="contact-section section-padding" id="section_6">
            <div class="container">
                <div class="row">

                    <div class="col-lg-8 col-12 mx-auto">
                        <h2 class="text-center mb-4"  style="color: white" >Interested? Let's talk</h2>

                        <nav class="d-flex justify-content-center">
                            <div class="nav nav-tabs align-items-baseline justify-content-center" id="nav-tab"
                                role="tablist">
                                <button class="nav-link active" id="nav-ContactForm-tab" data-bs-toggle="tab"
                                    data-bs-target="#nav-ContactForm" type="button" role="tab"
                                    aria-controls="nav-ContactForm" aria-selected="false">
                                    <h5>Contact Form</h5>
                                </button>

                                <button class="nav-link" id="nav-ContactMap-tab" data-bs-toggle="tab"
                                    data-bs-target="#nav-ContactMap" type="button" role="tab"
                                    aria-controls="nav-ContactMap" aria-selected="false">
                                    <h5>Google Maps</h5>
                                </button>
                            </div>
                        </nav>

                        <div class="tab-content shadow-lg mt-5" id="nav-tabContent">
                            <div class="tab-pane fade show active" id="nav-ContactForm" role="tabpanel"
                                aria-labelledby="nav-ContactForm-tab">

                                <form class="custom-form contact-form mb-5 mb-lg-0" name="contact" action="{% url 'eventApp:contact' %}" method="post" role="form">
                                    {% csrf_token %}
                                    <div class="contact-form-body">
                                        <div class="row">
                                            <div class="col-lg-6 col-md-6 col-12">
                                                <input type="text" name="name" id="name" class="form-control" placeholder="Name" required>
                                            </div>

                                            <div class="col-lg-6 col-md-6 col-12">
                                                <input type="email" name="email" id="email" pattern="[^ @]*@[^ @]*" class="form-control" placeholder="Email address" required>
                                            </div>
                                        </div>

                                        <input type="text" name="company" id="company" class="form-control" placeholder="Company" required>

                                        <textarea name="message" rows="3" class="form-control" id="message" placeholder="Message"></textarea>

                                        <div class="col-lg-4 col-md-10 col-8 mx-auto">
                                            <button type="submit" class="form-control">Send message</button>
                                        </div>
                                    </div>
                                </form>


                            </div>

                            <div class="tab-pane fade" id="nav-ContactMap" role="tabpanel"
                                aria-labelledby="nav-ContactMap-tab">
                                <iframe class="google-map"
                                    src="https://www.google.com/maps/d/embed?mid=17iRISR3SxB_LJno01O0UMqKiJKg&hl=en&ehbc=2E312F"
                                    width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy"
                                    referrerpolicy="no-referrer-when-downgrade"></iframe>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </section>

    {#    CONTACT SECTION ENDS HERE .... #}

{% endblock %}

eventApp/templates/pricing.html
{% extends 'base.html' %}

{% load static %}

{% block main  %}

     <style>
        body{
            background-color: rgba(0, 0, 0, 0.72);

        }
    </style>

    {#    PRICING SECTION STARTS HERE .... #}
        <section class="pricing-section section-padding section-bg" id="section_5">
            <div class="container">
                <div class="row">

                    <div class="col-lg-8 col-12 mx-auto">
                        <h2 class="text-center mb-4">Plans, you' love</h2>
                    </div>

                    <div class="col-lg-6 col-12">
                        <div class="pricing-thumb">
                            <div class="d-flex">
                                <div>
                                    <h3><small>Early Bird</small> Kshs. 5</h3>

                                    <p>Including good things:</p>
                                </div>

                             <h2 class="pricing-tag ms-auto">Save up to <span>50%</span></h2>
                            </div>

                            <ul class="pricing-list mt-3">
                                <li class="pricing-list-item">platform for potential customers</li>

                                <li class="pricing-list-item">digital experience</li>

                                <li class="pricing-list-item">high-quality sound</li>

                                <li class="pricing-list-item">standard content</li>
                            </ul>

                            <a class="link-fx-1 color-contrast-higher mt-4" href="{% url 'eventApp:ticket' %}">
                                <span>Buy Ticket</span>
                                <svg class="icon" viewBox="0 0 32 32" aria-hidden="true">
                                    <g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round">
                                        <circle cx="16" cy="16" r="15.5"></circle>
                                        <line x1="10" y1="18" x2="16" y2="12"></line>
                                        <line x1="16" y1="12" x2="22" y2="18"></line>
                                    </g>
                                </svg>
                            </a>
                        </div>
                    </div>

                    <div class="col-lg-6 col-12 mt-4 mt-lg-0">
                        <div class="pricing-thumb">
                            <div class="d-flex">
                                <div>
                                    <h3><small>Standard</small> Kshs. 10</h3>

                                    <p>What makes a premium Connect Fiesta?</p>
                                </div>
                            </div>

                            <ul class="pricing-list mt-3">
                                <li class="pricing-list-item">platform for potential customers</li>

                                <li class="pricing-list-item">digital experience</li>

                                <li class="pricing-list-item">high-quality sound</li>

                                <li class="pricing-list-item">premium content</li>

                                <li class="pricing-list-item">live chat support</li>
                            </ul>

                            <a class="link-fx-1 color-contrast-higher mt-4" href="{% url 'eventApp:ticket' %}">
                                <span>Buy Ticket</span>
                                <svg class="icon" viewBox="0 0 32 32" aria-hidden="true">
                                    <g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round">
                                        <circle cx="16" cy="16" r="15.5"></circle>
                                        <line x1="10" y1="18" x2="16" y2="12"></line>
                                        <line x1="16" y1="12" x2="22" y2="18"></line>
                                    </g>
                                </svg>
                            </a>
                        </div>
                    </div>

                </div>
            </div>
        </section>
    {#    PRICING SECTION ENDS HERE .... #}

{% endblock %}

eventApp/templates/success.html
{% extends 'base.html' %}

{% load static %}

{% block main %}
    <style>
        .centered-content {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        img {
            max-width: 100%;
            height: auto;
            display: block;
            margin: 0 auto;
        }

        h4 {
            margin-top: 20px;
        }
    </style>

    <div class="centered-content">

        <img src="{% static 'images/success.png' %}" alt="Success Image">

        <h4>See you there in the event <a href="{% url 'eventApp:index'  %}">Go Back</a></h4>

    </div>

{% endblock %}